import { useCallback, useEffect, useMemo, useRef, useState } from 'react'

import { useAuthStore } from '../auth/store'
import { API_BASE } from '../../shared/api/client'
import { useSSE, type SSEError } from '../../shared/hooks/useSSE'
import ChatMessage from './ChatMessage'
import { useSessionStore } from './store'
import type { SessionResponse } from './types'

interface ChatPanelProps {
  session: SessionResponse
}

/**
 * Parse the set of file paths in a unified diff.
 *
 * Kept inline (not imported from a shared util) because this is the
 * only consumer on the frontend — the backend has its own equivalent
 * in `infrastructure/diff_refs.py`. If a second consumer appears,
 * promote this to `shared/utils/diffFilePaths.ts`.
 *
 * Falls back to ``+++ b/`` / ``--- a/`` headers for diffs that do not
 * carry a ``diff --git`` line (some GitHub cross-fork PRs + raw unified
 * diffs generated by non-git tools). Mirrors the backend
 * ``parse_diff_file_paths`` fallback so UX-DR6's auto-switch works for
 * every diff shape the backend can produce.
 */
function parseDiffFilePaths(diff: string): string[] {
  const seen = new Set<string>()
  const ordered: string[] = []

  const push = (path: string | undefined) => {
    if (!path) return
    const trimmed = path.trim()
    if (!trimmed || trimmed === '/dev/null' || seen.has(trimmed)) return
    seen.add(trimmed)
    ordered.push(trimmed)
  }

  const gitLineRegex = /^diff --git a\/(.+?) b\/(.+?)$/gm
  let match: RegExpExecArray | null
  while ((match = gitLineRegex.exec(diff)) !== null) {
    push(match[1])
    push(match[2])
  }

  // Fall back on `+++ b/...` / `--- a/...` headers. Run these
  // unconditionally so `diff --git`-less diffs still populate the list
  // AND so we pick up any paths that the `diff --git` branch failed to
  // surface (e.g. the parent regex skipped an odd rename encoding).
  const plusHeaderRegex = /^\+\+\+ b\/(.+?)$/gm
  while ((match = plusHeaderRegex.exec(diff)) !== null) {
    push(match[1])
  }
  const minusHeaderRegex = /^--- a\/(.+?)$/gm
  while ((match = minusHeaderRegex.exec(diff)) !== null) {
    push(match[1])
  }

  return ordered
}

/**
 * ChatPanel — the left panel of the split view.
 *
 * Story 3.3 replaces the Story 3.2 placeholder with a live chat
 * message list driven by Server-Sent Events. Key behaviours:
 *
 * - Opens a single SSE stream on mount (closed on unmount).
 * - Renders each committed message + the in-flight streaming message.
 * - Calls `setActiveFile` when a committed question references files.
 * - Auto-scrolls to bottom on each token append UNLESS the user has
 *   scrolled up manually (no "Jump to latest" button — that's out of
 *   scope for 3.3).
 * - Shows the "Waiting for the first question..." placeholder until
 *   either a streaming message or a committed message exists.
 * - Falls back to an inline error banner on stream errors.
 */
export default function ChatPanel({ session }: ChatPanelProps) {
  const messages = useSessionStore((s) => s.messages)
  const streamingQuestion = useSessionStore((s) => s.streamingQuestion)
  const appendQuestionToken = useSessionStore((s) => s.appendQuestionToken)
  const commitStreamingQuestion = useSessionStore((s) => s.commitStreamingQuestion)
  const highlightActiveFile = useSessionStore((s) => s.highlightActiveFile)

  const [sseError, setSseError] = useState<string | null>(null)

  const diffFilePaths = useMemo(() => parseDiffFilePaths(session.diff), [session.diff])

  const scrollContainerRef = useRef<HTMLDivElement | null>(null)
  const autoScrollRef = useRef(true)

  const handleScroll = useCallback(() => {
    const el = scrollContainerRef.current
    if (!el) return
    autoScrollRef.current = el.scrollTop >= el.scrollHeight - el.clientHeight - 50
  }, [])

  // Auto-scroll on new content if the user has not scrolled up.
  useEffect(() => {
    const el = scrollContainerRef.current
    if (!el) return
    if (autoScrollRef.current) {
      el.scrollTop = el.scrollHeight
    }
  }, [messages.length, streamingQuestion?.text])

  const handleQuestionToken = useCallback(
    (payload: { questionId: string; token: string; number: number; total: number }) => {
      appendQuestionToken(payload.questionId, payload.token, payload.number, payload.total)
    },
    [appendQuestionToken],
  )

  const handleQuestion = useCallback(
    (payload: {
      question_id: string
      text: string
      number: number
      total: number
      file_refs: string[]
    }) => {
      commitStreamingQuestion(payload)
      if (payload.file_refs.length > 0) {
        // AC #11: switch to the first referenced file AND trigger the
        // 300ms accent-blue highlight flash on its tab. Using
        // ``highlightActiveFile`` (instead of ``setActiveFile``)
        // deliberately ticks the store's highlight counter — that is
        // the signal DiffViewer listens to for the visual flash.
        const firstRef = payload.file_refs.find((ref) => diffFilePaths.includes(ref))
        if (firstRef) {
          const index = diffFilePaths.indexOf(firstRef)
          if (index >= 0) {
            highlightActiveFile(index)
          }
        }
      }
    },
    [commitStreamingQuestion, diffFilePaths, highlightActiveFile],
  )

  const handleError = useCallback((err: SSEError) => {
    // P6: every error kind now surfaces something to the user. Parse
    // errors used to be silently dropped, which made production
    // debugging blind. We log parse errors (rare — they indicate a
    // server-side JSON drift) in addition to the banner.
    if (err.kind === 'server') {
      setSseError('The question stream reported an error. Please retry.')
    } else if (err.kind === 'network') {
      setSseError('Connection lost. Reconnecting...')
    } else if (err.kind === 'parse') {
      console.warn('[useSSE] parse error', err.payload)
      setSseError('A malformed frame was received from the server.')
    }
  }, [])

  const handleDone = useCallback(() => {
    setSseError(null)
  }, [])

  // Auth: EventSource cannot send custom headers, so the access token
  // travels in the URL. Backend `get_current_user` accepts both
  // `Authorization: Bearer` and `?access_token=`. The URL is also
  // absolute (against `API_BASE`) because the frontend dev server
  // (`localhost:5173`) does not proxy to the API (`localhost:8000`).
  const accessToken = useAuthStore((s) => s.accessToken)
  const sseEnabled = session.status !== 'completed' && accessToken !== null
  const sseUrl = accessToken
    ? `${API_BASE}/api/v1/sessions/${session.id}/stream?access_token=${encodeURIComponent(accessToken)}`
    : ''
  useSSE({
    url: sseUrl,
    enabled: sseEnabled,
    onQuestionToken: handleQuestionToken,
    onQuestion: handleQuestion,
    onDone: handleDone,
    onError: handleError,
  })

  const hasContent = messages.length > 0 || streamingQuestion !== null

  return (
    <div
      className="h-full w-full bg-primary flex flex-col overflow-hidden"
      data-testid="chat-panel"
    >
      <div
        ref={scrollContainerRef}
        onScroll={handleScroll}
        className="flex-1 overflow-y-auto flex flex-col"
      >
        <div className="max-w-[720px] w-full mx-auto px-4 py-6 flex-1 flex flex-col">
          {sseError && (
            <div
              role="alert"
              data-testid="chat-error-banner"
              className="text-[13px] text-text-secondary"
              style={{
                padding: 12,
                marginBottom: 16,
                borderRadius: 8,
                backgroundColor: 'rgba(255, 69, 58, 0.15)',
                color: '#ff453a',
              }}
            >
              {sseError}
            </div>
          )}

          {!hasContent && (
            <div className="flex-1 flex items-center justify-center">
              <p className="text-[14px] text-text-muted" data-testid="chat-placeholder">
                Waiting for the first question...
              </p>
            </div>
          )}

          {hasContent && (
            <div data-testid="chat-message-list">
              {messages.map((m) => (
                <ChatMessage key={m.id} message={m} />
              ))}
              {streamingQuestion && (
                <ChatMessage key={streamingQuestion.id} message={streamingQuestion} />
              )}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
