"""add byok_configs table and suppression_labels to installations

Revision ID: 792dfdfd0924
Revises: bcc0b5382ffd
Create Date: 2026-04-09 19:04:21.261778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '792dfdfd0924'
down_revision: Union[str, None] = 'bcc0b5382ffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('byok_configs',
    sa.Column('installation_id', sa.Uuid(), nullable=False),
    sa.Column('encrypted_api_key', sa.String(length=1024), nullable=False),
    sa.Column('key_status', sa.String(length=20), nullable=False),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('key_hint', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_byok_configs_installation_id'), 'byok_configs', ['installation_id'], unique=True)
    op.add_column('installations', sa.Column('suppression_labels', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('installations', 'suppression_labels')
    op.drop_index(op.f('ix_byok_configs_installation_id'), table_name='byok_configs')
    op.drop_table('byok_configs')
    # ### end Alembic commands ###
