"""add sessions table

Revision ID: 9036c7377667
Revises: 98dc1b6e754e
Create Date: 2026-04-10 07:43:51.510193

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9036c7377667'
down_revision: str | None = '98dc1b6e754e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sessions',
    sa.Column('installation_id', sa.Uuid(), nullable=False),
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('repo_full_name', sa.String(length=512), nullable=False),
    sa.Column('repo_owner', sa.String(length=255), nullable=False),
    sa.Column('repo_name', sa.String(length=255), nullable=False),
    sa.Column('pr_number', sa.Integer(), nullable=False),
    sa.Column('pr_title', sa.String(length=1024), nullable=False),
    sa.Column('pr_head_sha', sa.String(length=40), nullable=False),
    sa.Column('pr_diff_url', sa.String(length=1024), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, server_default='pending'),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['installation_id'], ['installations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('installation_id', 'repo_full_name', 'pr_number', 'role', name='uq_sessions_installation_pr_role')
    )
    op.create_index(op.f('ix_sessions_github_installation_id'), 'sessions', ['github_installation_id'], unique=False)
    op.create_index(op.f('ix_sessions_installation_id'), 'sessions', ['installation_id'], unique=False)
    op.create_index(op.f('ix_sessions_repo_full_name'), 'sessions', ['repo_full_name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sessions_repo_full_name'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_installation_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_github_installation_id'), table_name='sessions')
    op.drop_table('sessions')
    # ### end Alembic commands ###
