"""add installations table

Revision ID: bcc0b5382ffd
Revises: f91a5f49775b
Create Date: 2026-04-09 17:21:33.577851

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcc0b5382ffd'
down_revision: Union[str, None] = 'f91a5f49775b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('installations',
    sa.Column('github_installation_id', sa.BigInteger(), nullable=False),
    sa.Column('account_login', sa.String(length=255), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('account_type', sa.String(length=50), nullable=False),
    sa.Column('repository_selection', sa.String(length=20), nullable=False),
    sa.Column('app_slug', sa.String(length=255), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('permissions', sa.JSON(), nullable=True),
    sa.Column('events', sa.JSON(), nullable=True),
    sa.Column('suspended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_installations_github_installation_id'), 'installations', ['github_installation_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_installations_github_installation_id'), table_name='installations')
    op.drop_table('installations')
    # ### end Alembic commands ###
